// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKyEHBbPwxJ8RqHr0KTZWbrYpBxaWtT_Y',
    appId: '1:810018335794:web:a1e723c010bf2aec46e02b',
    messagingSenderId: '810018335794',
    projectId: 'cheese-cream-cheese',
    authDomain: 'cheese-cream-cheese.firebaseapp.com',
    storageBucket: 'cheese-cream-cheese.appspot.com',
    measurementId: 'G-DJCZHFLJVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSMhn9JstLciDuQ-VJDzWOD7AoVdyz_eA',
    appId: '1:810018335794:android:9bafc8d16e9c320146e02b',
    messagingSenderId: '810018335794',
    projectId: 'cheese-cream-cheese',
    storageBucket: 'cheese-cream-cheese.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuuB7aoY0ujqk_jSPnCGtaophUmX9bE84',
    appId: '1:810018335794:ios:8075d521b12c8ffc46e02b',
    messagingSenderId: '810018335794',
    projectId: 'cheese-cream-cheese',
    storageBucket: 'cheese-cream-cheese.appspot.com',
    iosBundleId: 'com.example.creamCheeseCream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuuB7aoY0ujqk_jSPnCGtaophUmX9bE84',
    appId: '1:810018335794:ios:31b0693818324fdd46e02b',
    messagingSenderId: '810018335794',
    projectId: 'cheese-cream-cheese',
    storageBucket: 'cheese-cream-cheese.appspot.com',
    iosBundleId: 'com.example.creamCheeseCream.RunnerTests',
  );
}
